import { Trend } from "./types";

const emotions = (values: number[]) => Object.fromEntries(["Excitement", "Supportive", "Anxiety", "Sarcasm", "Against", "Neutral"].map((name, index) => [name, values[index]])) as Trend["emotion"];
const series = (seed: number, growth: number) => Array.from({ length: 25 }, (_, i) => Math.max(15, Math.round(31 + i * growth / 80 + Math.sin(i * .8 + seed) * 11 + ((i * seed) % 9))));

export const demoTrends: Trend[] = [
  { id: "genai", name: "Generative AI", category: "Technology", mentions: 5100000, reach: 38700000, growth: 94, leadingEmotion: "Excitement", description: "Large language models, image generators and code assistants are driving the defining technology conversation across urban India.", keywords: ["agentic workflows", "GPU import duty", "prompt engineer salary", "on-device models", "AI in campus placements"], hubs: ["Bengaluru", "Hyderabad", "Delhi", "Mumbai"], series: series(2, 94), emotion: emotions([34,22,17,12,9,6]), platforms: [{name:"X",share:38,color:"#1a73e8"},{name:"Instagram",share:24,color:"#6b9cf0"},{name:"Reddit",share:22,color:"#9dbef5"},{name:"Telegram",share:16,color:"#d8e7ff"}], events: [{label:"Bengaluru dev meetup thread",value:"41K mentions/hr",at:42},{label:"Pricing change announcement",value:"63K mentions/hr",at:78}] },
  { id: "ipl", name: "IPL auction buzz", category: "Sports", mentions: 4300000, reach: 52100000, growth: 265, leadingEmotion: "Excitement", description: "Retention lists, marquee-lot bidding and captaincy speculation are driving explosive short-term fan conversation.", keywords: ["retention list leak", "marquee lot price", "captaincy rumour", "auction purse cap", "impact player rule"], hubs: ["Mumbai", "Chennai", "Kolkata", "Bengaluru"], series: series(4, 265), emotion: emotions([41,18,9,19,7,6]), platforms: [{name:"X",share:41,color:"#1a73e8"},{name:"Instagram",share:31,color:"#6b9cf0"},{name:"Reddit",share:17,color:"#9dbef5"},{name:"Telegram",share:11,color:"#d8e7ff"}], events: [{label:"Retention list leak",value:"88K mentions/hr",at:20},{label:"Auction day live bidding",value:"132K mentions/hr",at:70}] },
  { id: "upsc", name: "UPSC 2026 prep", category: "Education", mentions: 2800000, reach: 21400000, growth: 212, leadingEmotion: "Anxiety", description: "Notification dates, mock series and coaching-fee complaints dominate aspirant channels in this window.", keywords: ["prelims date shift", "optional subject swap", "free mock series", "Delhi coaching fees", "answer key row"], hubs: ["Lucknow", "Patna", "Delhi", "Jaipur"], series: series(6, 212), emotion: emotions([16,24,31,9,6,14]), platforms: [{name:"X",share:20,color:"#1a73e8"},{name:"Instagram",share:17,color:"#6b9cf0"},{name:"Reddit",share:18,color:"#9dbef5"},{name:"Telegram",share:45,color:"#d8e7ff"}], events: [{label:"Notification date leak",value:"28K mentions/hr",at:35},{label:"Result thread",value:"52K mentions/hr",at:88}] },
  { id: "monsoon", name: "Monsoon flooding", category: "Weather & Civic", mentions: 2600000, reach: 30800000, growth: 181, leadingEmotion: "Supportive", description: "Relief-camp coordination, IMD alerts and waterlogging complaints are spiking across flood-hit districts.", keywords: ["relief camp list", "IMD red alert", "waterlogging complaint", "boat rescue request", "flood relief fund"], hubs: ["Assam", "Mumbai", "Kochi", "Patna"], series: series(8, 181), emotion: emotions([4,26,33,8,21,8]), platforms: [{name:"X",share:35,color:"#1a73e8"},{name:"Instagram",share:16,color:"#6b9cf0"},{name:"Reddit",share:12,color:"#9dbef5"},{name:"Telegram",share:37,color:"#d8e7ff"}], events: [{label:"IMD red alert issued",value:"71K mentions/hr",at:15},{label:"Relief-camp list shared",value:"61K mentions/hr",at:55}] }
];

/** Set NEXT_PUBLIC_API_URL=https://your-api.example.com to connect the backend. */
export async function getTrends(): Promise<Trend[]> {
  const url = process.env.NEXT_PUBLIC_API_URL;
  if (!url) return demoTrends;
  try { const response = await fetch(`${url}/api/trends`, { next: { revalidate: 30 } }); return response.ok ? response.json() : demoTrends; } catch { return demoTrends; }
}

export async function getTrend(id: string) { return (await getTrends()).find((trend) => trend.id === id) ?? demoTrends[0]; }
